on: [push]

jobs:
  testactions_job:
    runs-on: ubuntu-latest
    name: A job to test the multi architecture action
    steps:
    - name: Run some commands on arm64
      id: runcmd
      uses: uraimo/run-on-arch-action@master
      with:
        architecture: aarch64
        distribution: stetch
        run: |
          go version
          echo ::set-output name=uname::$(go version)
    - name: Get the output
      run: |
        echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
